### ISSUE TITLE
Handle connection errors to Infura

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/service-ethereum-erc20#14]
In some cases, the data sent by Infura are not valid (probably when the connection is lost). In that case the error is caught but nothing is restarted. We should make sure that the listener is restarted either by managing this kind of error in the service or by stopping the process that will let docker restart the all service.

This bug actually freeze the service and no events are sent anymore.

Debug info:
```
service | Error: Invalid JSON RPC response: ""
service |     at Object.InvalidResponse (/app/node_modules/web3-core-helpers/src/errors.js:42:16)
service |     at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/src/index.js:87:32)
service |     at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
service |     at XMLHttpRequest._setReadyState (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
service |     at XMLHttpRequest._onHttpRequestError (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
service |     at ClientRequest.<anonymous> (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
service |     at ClientRequest.emit (events.js:182:13)
service |     at TLSSocket.socketErrorListener (_http_client.js:391:9)
service |     at TLSSocket.emit (events.js:182:13)
service |     at emitErrorNT (internal/streams/destroy.js:82:8)
service |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
service |     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by antho1404** [comment]
Another kind of errors that occurs
```
Error: Invalid JSON RPC response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"
```
